# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29148a32d3c880d1e53e5cfa743f1b3286c8fb119a69fc174db51c0a3d6f612abd68cdacc951c83a14a75e09fdb290e01c4478a4d3607e7a9e8b0db3a07bfeb2

test:
  secret_key_base: 5a217436d9c7970b19b21e1bef68210c4962e88286d65e866127becdc124e3e6971f556228b278c8e47c655a5e9627a486d697ebaa65bb3db6997148536ffcb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
